// <auto-generated />
namespace Sms_recive_web_service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class denemeee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(denemeee));
        
        string IMigrationMetadata.Id
        {
            get { return "202005230401085_denemeee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
